name: Release AppImage x86_64

on: [workflow_dispatch, workflow_call]

env:
  APPIMAGETOOL_VERSION: "13"
  APP_SHORTNAME: "md3"
  APP_LONGNAME: "MenderD3"

jobs:
  release-appimage-x86_64:
    runs-on: ubuntu-22.04  # Use oldest distro that supports Qt6
    timeout-minutes: 10

    steps:
      - name: Get CPU count
        run: |
          NPROC=$(python3 -c 'import multiprocessing; print(multiprocessing.cpu_count())')
          echo "NPROC=$NPROC" >> $GITHUB_ENV
          echo CPU count = $NPROC

      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      # cf. https://github.com/libsdl-org/SDL/blob/main/docs/README-linux.md
      - name: Get build dependencies from APT  
        run: |
          sudo apt update
          sudo apt install -y qt6-base-dev libgl-dev libglu1-mesa-dev libfuse2

      - name: Configure
        run: qmake6 -o Makefile src/md3.pro

      - name: Prepare artifact names
        run: |
          APP_VERSION="0.2.7"
          ARTIFACT_NAME="${{env.APP_SHORTNAME}}-$APP_VERSION-linux-x86_64.AppImage"
          echo "APP_VERSION=$APP_VERSION" >> $GITHUB_ENV
          echo "ARTIFACT_NAME=$ARTIFACT_NAME" >> $GITHUB_ENV

      - name: Build
        run: make -j ${{ env.NPROC }}

      - name: Prepare AppDir
        run: bash packaging/prepare_appimage_appdir.sh ${{env.APP_SHORTNAME}}

      - name: Make AppImage
        run: |
          wget https://github.com/AppImage/AppImageKit/releases/download/${{env.APPIMAGETOOL_VERSION}}/appimagetool-x86_64.AppImage
          chmod +x appimagetool-x86_64.AppImage
          ./appimagetool-x86_64.AppImage --no-appstream build/${{env.APP_SHORTNAME}}.AppDir build/${{env.ARTIFACT_NAME}}

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: ${{env.ARTIFACT_NAME}}
          path: build/${{env.ARTIFACT_NAME}}
