name: Release Windows

on: [workflow_dispatch, workflow_call]

env:
  APP_SHORTNAME: "md3"
  APP_LONGNAME: "MenderD3"

jobs:
  release-windows:
    runs-on: windows-2022
    timeout-minutes: 20

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Install MSVC
        uses: ilammy/msvc-dev-cmd@v1

      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          version: "6.7.*"

      - name: Configure
        run: qmake6 -o Makefile src/md3.pro

      - name: Prepare artifact names
        run: |
          $FOLDER_NAME = "${{env.APP_LONGNAME}}"
          $ARTIFACT_NAME = "${{env.APP_SHORTNAME}}-windows-x64.zip"
          echo "FOLDER_NAME=$FOLDER_NAME" >> $env:GITHUB_ENV
          echo "ARTIFACT_NAME=$ARTIFACT_NAME" >> $env:GITHUB_ENV

      - name: Build
        run: make

      - name: Zip it up
        run: |
          move Release "${{env.FOLDER_NAME}}"
          Compress-Archive -Path "${{env.FOLDER_NAME}}" -DestinationPath ${{env.ARTIFACT_NAME}} -CompressionLevel Optimal

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: ${{env.ARTIFACT_NAME}}
          path: ${{env.ARTIFACT_NAME}}
