name: Release Windows

on: [workflow_dispatch, workflow_call]

env:
  GAME_SHORTNAME: "md3"
  GAME_LONGNAME: "MenderD3"

jobs:
  release-windows:
    runs-on: windows-2022
    timeout-minutes: 20

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Install MSVC
        uses: ilammy/msvc-dev-cmd@v1

      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          version: "6.7.*"

      - name: Configure
        run: qmake6 -o Makefile src/md3.pro

      - name: Prepare artifact names
        run: |
          $GAME_VERSION = Get-Content build/version.txt
          $FOLDER_NAME = "${{env.GAME_LONGNAME}} $GAME_VERSION"
          $ARTIFACT_NAME = "${{env.GAME_SHORTNAME}}-$GAME_VERSION-windows-x64.zip"
          echo "GAME_VERSION=$GAME_VERSION" >> $env:GITHUB_ENV
          echo "FOLDER_NAME=$FOLDER_NAME" >> $env:GITHUB_ENV
          echo "ARTIFACT_NAME=$ARTIFACT_NAME" >> $env:GITHUB_ENV

      - name: Build
        run: make

      # Note: if the game contains C++, you should also copy msvcp140.dll and vcruntime140_1.dll
      - name: Copy extra stuff
        run: |
          cmake --install build --prefix build/install
          copy build/ReadMe.txt build/Release
          copy build/install/bin/vcruntime140.dll build/Release

      - name: Zip it up
        run: |
          move build/Release "build/${{env.FOLDER_NAME}}"
          Compress-Archive -Path "build/${{env.FOLDER_NAME}}" -DestinationPath build/${{env.ARTIFACT_NAME}} -CompressionLevel Optimal

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: ${{env.ARTIFACT_NAME}}
          path: build/${{env.ARTIFACT_NAME}}
